/*$file${src::blink.c} #####################################################*/
/*
* Model: blink.qm
* File:  ${src::blink.c}
*
* This code has been generated by QM 4.4.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${src::blink.c} ##################################################*/

// QPC blink sample (c) Dmitry Ponyatov <dponyatov@gmail.com>

// кириллица

int main() {
}
